export const ADD_NUMBER = 'ADD_NUMBER'
export const Set_indexData = 'Set_indexData'
export const Set_user_info = 'Set_user_info'
export const Set_user_orders = 'Set_user_orders'
export const Set_orders_banner = 'Set_orders_banner'
